### ISSUE TITLE
Use commit sha instead of tag

### ISSUE THREAD

**Issue by Globegitter** [bzl-io/bzl#1]
First of all thanks for this tool, it is really useful - one thing we end up doing quite regularly is using a version based on a commit rather than the latest release (e.g. to get a bugfix quicker etc). It would be great if e.g. `bazel use rules_docker 3332026921c918c9bfaa94052578d0ca578aab66` was also valid.

**Comment by pcj** [comment]
Yes I agree, should not be too hard to do this.

**Comment by pcj** [comment]
Fidex in #3
